import type { Config } from 'tailwindcss';

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@moondesignsystem/react/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        badook: {
          'primary': '#55c8e4',
          'primary-content': '#141414',
          'secondary': '#8c5fa8',
          'secondary-content': '#FFFFFF',
          'accent': '#2d1b4e',
          'accent-content': '#FFFFFF',
          'neutral': '#1F2937',
          'neutral-content': '#F9FAFB',
          'base-100': '#FFFFFF',
          'base-200': '#F3F4F6',
          'base-300': '#E5E7EB',
          'base-content': '#111827',
          'info': '#0EA5E9',
          'info-content': '#FFFFFF',
          'success': '#10B981',
          'success-content': '#FFFFFF',
          'warning': '#F59E0B',
          'warning-content': '#FFFFFF',
          'error': '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
        },
      },
      {
        'badook-dark': {
          'color-scheme': 'dark',
          'primary': '#55c8e4',
          'primary-content': '#141414',
          'secondary': '#8c5fa8',
          'secondary-content': '#FFFFFF',
          'accent': '#b794d9',
          'accent-content': '#141414',
          'neutral': '#1E293B',
          'neutral-content': '#E5E5E5',
          'base-100': '#0A0A0A',
          'base-200': '#141414',
          'base-300': '#262626',
          'base-content': '#E5E5E5',
          'info': '#0EA5E9',
          'info-content': '#FFFFFF',
          'success': '#10B981',
          'success-content': '#FFFFFF',
          'warning': '#F59E0B',
          'warning-content': '#141414',
          'error': '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
        },
      },
    ],
  },
} satisfies Config;
