-- Add exception action reasons to LineItemEditReason enum
ALTER TYPE "LineItemEditReason" ADD VALUE IF NOT EXISTS 'OVERRIDE_SUBSTITUTE';
ALTER TYPE "LineItemEditReason" ADD VALUE IF NOT EXISTS 'OVERRIDE_PRICE_APPROVED';
ALTER TYPE "LineItemEditReason" ADD VALUE IF NOT EXISTS 'OVERRIDE_UNIT_CORRECTION';
ALTER TYPE "LineItemEditReason" ADD VALUE IF NOT EXISTS 'FLAG_DUPLICATE';
