import { useTranslation } from 'react-i18next';
import { POSectionTitle } from '../../OverviewPage/components/POSectionTitle';
import { ProjectSelector } from '../../OverviewPage/components/ProjectSelector';
import type { useUploadDocumentForm } from '../hooks/useUploadDocumentForm';

interface Props {
  form: ReturnType<typeof useUploadDocumentForm>;
}

const INPUT = 'w-full px-3 py-2.5 border border-base-300 rounded-lg text-sm placeholder:text-base-content/40 focus:outline-none focus:ring-2 focus:ring-secondary/20 focus:border-secondary/50';

export const UploadOrderDetailsSection = ({ form }: Props) => {
  const { t } = useTranslation('projects');
  const dt = form.docType;

  return (
    <>
      <POSectionTitle icon="🏗️" title={t(`upload.sectionTitle_${dt}`, t('createPO.orderDetails'))} />
      <div className="grid grid-cols-2 gap-4 mt-4">
        <div>
          <label className="block text-sm font-medium text-base-content/60 mb-1.5">{t('createPO.project')}</label>
          {form.showProjectSelector ? (
            <ProjectSelector
              projects={form.activeProjects}
              value={form.selectedProjectId}
              onChange={form.setSelectedProjectId}
              onCreateProject={form.handleCreateProject}
            />
          ) : (
            <div className="flex items-center px-3 py-2.5 border border-base-300 rounded-lg bg-base-200 text-sm text-base-content/50 font-medium">
              {form.projectName}
            </div>
          )}
        </div>
        <div>
          <label className="block text-sm font-medium text-base-content/60 mb-1.5">{t(`upload.docNumber_${dt}`, t('createPO.orderNumber'))}</label>
          <div className="flex items-center gap-2 relative">
            <span className="absolute start-3 text-base-content/40">#</span>
            <input type="text" value={form.docNumber} onChange={(e) => form.setDocNumber(e.target.value)} placeholder={t('upload.autoGenerated', 'Auto-generated')} className={`${INPUT} ps-7 font-mono`} />
          </div>
        </div>
        <div>
          <label className="block text-sm font-medium text-base-content/60 mb-1.5">{t(`upload.docDate_${dt}`, t('createPO.deliveryDate'))}</label>
          <input type="date" value={form.deliveryDate} onChange={(e) => form.setDeliveryDate(e.target.value)} className={INPUT} />
        </div>
        <div>
          <label className="block text-sm font-medium text-base-content/60 mb-1.5">{t('createPO.paymentTerms')}</label>
          <input type="text" value={form.paymentTerms} onChange={(e) => form.setPaymentTerms(e.target.value)} placeholder={t('createPO.paymentTermsPlaceholder')} className={INPUT} />
        </div>
      </div>
    </>
  );
};
